### PR TITLE
@joeyAghion => Adds a `sections` integration test

### PR DESCRIPTION
**Pull request by kanaabe**
Yesterday's failures could have definitely prevented with this simple check

### CODE REVIEW

**Comment by joeyAghion** [comment]
This is great, especially if minor package upgrades could have this impact.

Did you confirm that this test would _fail_ on e3281620498dfef72fa50767b81e21e6e5113141?

**Comment by kanaabe** [comment]
Ha good call, it turns out the dependency issue happens in GraphQL, not our REST endpoints. I'll have to set up another test. I'll keep this one open until then.

**Comment by joeyAghion** [comment]
😅 Glad I asked.

And keep this in any case... it's a good addition.

**Comment by kanaabe** [comment]
@joeyAghion this is now updated with an integration test on our GraphQL endpoint 😄

**Comment by joeyAghion** [comment]
Excellent, thanks.

**Comment by eessex** [comment]
@kanaabe was this working with the react 16 setup?  These are failing again on the new React 16 PR, maybe I missed a dependency of something -- 
screen shot 2018-01-10 at 6 50 26 pm

**Comment by eessex** [comment]
Ah just realized i missed a reverted commit -- this is working now 👍

**Pull request merged**
