### PR TITLE
Fix css path

### PR DESCRIPTION
**Pull request by damassi**
My previous branch was building off of old CSS; noticed these path issues when i blew away repo and reinstalled

### CODE REVIEW

**Comment by kanaabe** [comment]
`cannot create directory ‘public/assets’: No such file or directory` 🤔

**Comment by damassi** [comment]
Circle keeps hanging on Jest due to memory issues, trying this: https://vgpena.github.io/jest-circleci/

**Comment by kanaabe** [comment]
@damassi I thought that's what https://github.com/artsy/positron/pull/1658 is for?

**Comment by damassi** [comment]
I was going to close that pr from this one with a #superceded note

**Pull request merged**
