### PR TITLE
@eessex => Remove client-side sections

### PR DESCRIPTION
**Pull request by kanaabe**
Closes https://github.com/artsy/positron/issues/856

We should still support it in the API since we support the 2015 Venice Biennale section still. However, we should remove the ability to CRUD them.

### CODE REVIEW

**Comment by eessex** [comment]
goodbye sections! 
I have been noticing some weird action with the settings icon going black, is this what the new svg fixes or another issue?

**Comment by kanaabe** [comment]
Yep! It was actually kinda weird -- it was inheriting a fill style from a different SVG that had the same class name. So that new SVG simply changes the name of the class that's used.

**Comment by eessex** [comment]
:1st_place_medal:

**Comment by kanaabe** [comment]
Mergin this!

**Pull request merged**
