### PR TITLE
@kanaabe => Updated at bug in articles list

### PR DESCRIPTION
**Pull request by eessex**
Closes https://github.com/artsy/positron/issues/891

Add updated_at to article schema and query

### CODE REVIEW

**Comment by kanaabe** [comment]
This means people _could_ manipulate this field which I'm ok with but a new field in the schema means we should have a test!

**Comment by eessex** [comment]
Is there a way to include this in the query without adding it to the schema?  The application seems to crash without it.  Will add a test now.

**Comment by kanaabe** [comment]
Not that I know of. We're using the same schema in two ways, originally to control what can be saved, and now for presentation/queryable fields in GraphQL. So probably the right thing to do is eventually separate these out. I think for now it's fine to add `updated_at` to the schema.

**Comment by eessex** [comment]
The saving of this field is already tested against date here -- https://github.com/artsy/positron/blob/master/api/apps/articles/test/model/index.coffee#L435 -- and presentation here - https://github.com/artsy/positron/blob/master/api/apps/articles/test/model/index.coffee#L435

Is there another way we should be testing it?

**Comment by kanaabe** [comment]
Riight so the new functionality is that you can save `updated_at` as an input. As opposed to it being auto-generated. So we should have tests for both! Lmk if that makes sense.

**Comment by eessex** [comment]
Cool! That does make sense, just added more tests.

**Comment by kanaabe** [comment]
Great thanks!

**Pull request merged**
