### PR TITLE
[WIP] Adds S3 upload for separate ad asset bucket

### PR DESCRIPTION
**Pull request by kanaabe**
Pair sesh with @eessex on getting display assets uploaded to a different bucket!

### CODE REVIEW

**Comment by kanaabe** [comment]
So old, closing this.

**Comment by eessex** [comment]
we really should finish this!

**Comment by kanaabe** [comment]
Lol agree, but it's not being prioritized so no point in keeping it open. Feel free to work on it if you please! Branch is still there. I believe there's some cleanup and tests?

**Comment by eessex** [comment]
How can we get this on the list for working on in a sprint?

**Comment by kanaabe** [comment]
First step is to add it to the backlog, and then if there's similar work to be done in a sprint you can propose a project. People have proposed projects by posting in #dev or alternatively you can speak with a PM.

**Comment by kanaabe** [comment]
Do it!

**Pull request closed without merging**
