### PR TITLE
@zamiang Type cast objectid on related_articles

### PR DESCRIPTION
**Pull request by kanaabe**
Closes https://github.com/artsy/positron/issues/607
Totally forgot to do this... -.- 

Anyway this will map the ObjectId over `super_article.related_articles` when saving.

### CODE REVIEW

**Comment by zamiang** [comment]
Ah! Interesting. Should it also have a test :grin: ?

**Comment by zamiang** [comment]
But ya looks good to go - seems like this was just a regular thing for adding models that was missed.

**Comment by kanaabe** [comment]
Yep, we do the type casting because of this funny little issue: https://github.com/pebble/joi-objectid/issues/2#issuecomment-75189638

Good call, test coming!

**Comment by zamiang** [comment]
Seems like the build is stuck or something?

**Pull request merged**
